### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by MarcPinnell** [datamweb/codeigniter-multi-captcha#1]
Love the promise of this library, but having issues getting it to run. Followed the instructions you set, but when I try to pull up the contact form I get:

Call to undefined function CIMC_JS()

I looked at the short video you have online and noticed the command: setup:cimc --show

But when I run that, I get: Command "setup:cimc" not found.

In the video, there is a reference to a line in "generator" but there is nothing in the instructions for that.

Help!

**Comment by datamweb** [comment]
Hi @MarcPinnell , nice to have you here.
Regarding command `setup:cimc`, I was going to post it, but I left it because I didn't get any feedback.

Regarding receiving error, you need to load helper function **ci_multi_captcha**.
```php
helper(['ci_multi_captcha','form','url']);
```
To be honest, if I were to write this library today, I would consider many changes in its design. This was my first experience, I like it very much.

**Comment by MarcPinnell** [comment]
I removed all the stuff in the third party folder and then tried the composer install. No change. Where do I set all the paths and keys using the composer install?

**Comment by MarcPinnell** [comment]
I removed the composer install and went back to the manual for now. Added the helper and it is now working. 

Did you just update something. I would swear the install instructions changed in the last hour.

**Comment by MarcPinnell** [comment]
Sorry, one last question (I hope). I put the code you show on the contact form and it works great. But you also say I need to put something in a controller: "CIMC_FIELD('hcaptcha) => CIMC_RULE(),"

What controller? The contact form processor?

**Comment by datamweb** [comment]
> something in a controller: "CIMC_FIELD('hcaptcha) => CIMC_RULE(),"

see here : 

https://github.com/datamweb/codeIgniter-multi-captcha/blob/316b47f7e2c636e4adbd0f3dd555ae48e4b840f5/CIMultiCaptcha/Controllers/RateLimit.php#L79

**Comment by MarcPinnell** [comment]
It's already there... Seems to be working without me doing anything.

**Comment by datamweb** [comment]
No, it is not, you must define in the rules that you have a captcha, otherwise, if the captcha is not solved, it is possible to jump to the next step without checking the captcha answer.

**Comment by MarcPinnell** [comment]
Ok, you are correct. While it is showing the hcaptcha, it isn't actually stopping me from submitting form. So, I am confused on what step is missing from instructions.

In my contact form view file I have:

`<?php
	echo CIMC_JS('hcaptcha');
	echo CIMC_ERROR();
	echo CIMC_HTML(['captcha_name'=>'hcaptcha']);
?>`

I am still not clear on where I am supposed to add the line: 
`CIMC_FIELD('hcaptcha) => CIMC_RULE(),`

**Comment by datamweb** [comment]
Send the minimum controller code.

**Comment by datamweb** [comment]
It doesn't help. I'll record a video tomorrow.

**Comment by MarcPinnell** [comment]
Thanks for all your help so far!

**Comment by datamweb** [comment]
I will create a simple form with the controller, so you can understand, do you need anything else?

**Comment by MarcPinnell** [comment]
Nope I think that is the last piece. It is working fine except that you can skip the verification.

I am still using the composer install. Composer didn't remove it earlier when I thought I did. It started working when I redid the setup. Because of that I put the hcaptcha keys in the config file per instructions, but seems odd that I should be modifying the file that is inside vendor directory. If you are going to do another version, might want to move the keys to the .env file so they don't get overwritten when doing updates via composer.

**Comment by datamweb** [comment]
> If you are going to do another version, might want to move the keys to the .env file so they don't get overwritten when doing updates via composer.

Added two features:
1. Command `cimc:publish ` 
To use it, run the following command.
    ```console
    php spark cimc:publish
    ```
    Then go to **app/Config/MultiCaptchaCIConfig.php** and set the keys (or any other properties).

2. The use of env was added, just add the keys to the **.env** file as below for each captcha.(**The priority is if set with file env**)
    ```env
    multiCaptcha.arCaptcha.siteKey = 82ab22rpn4
    multiCaptcha.arCaptcha.secretKey = ld469lmgqq9ht2u6f7q4
    multiCaptcha.hCaptcha.siteKey = 82ab22rpn4
    multiCaptcha.hCaptcha.secretKey = ld469lmgqq9ht2u6f7q4
    # and ...
    ```

**Comment by MarcPinnell** [comment]
Nice work and fast! Can you explain what the publish command does?

**Comment by datamweb** [comment]
It just creates a copy of file **vendor\datamweb\codeIgniter-multi-captcha\CIMultiCaptcha\Config\MultiCaptchaCIConfig.php** with slightly changed contents in path **app\ConfigMultiCaptchaCIConfig.php** . 

This will make you not need to set in file **vendor\datamweb\codeIgniter-multi-captcha\CIMultiCaptcha\Config\MultiCaptchaCIConfig.php**.

In case of updating, there is no problem because the settings are made in file **app\ConfigMultiCaptchaCIConfig.php**, not **vendor\datamweb\codeIgniter-multi-captcha\CIMultiCaptcha\Config\MultiCaptchaCIConfig.php**.

**Comment by MarcPinnell** [comment]
Nice! I like that.

Were you able to put together the sample contact form?

**Comment by datamweb** [comment]
Yes, the only problem we have is that the government here has recently created many problems to use the Internet, in fact the file upload speed is so slow that it actually takes me several hours/day to upload.
Can the sample code be enough for you?

**Comment by MarcPinnell** [comment]
I have the captcha working on the contact form, but you can just ignore it and hit submit without it failing. Seems like I need something in my controller file (posted above). Just not sure what.

![Screenshot 2023-03-29 at 8 14 01 AM](https://user-images.githubusercontent.com/4871176/228585693-a1271d4a-184c-4bba-9035-1e4a325f36e2.png)

**Comment by datamweb** [comment]
>  but you can just ignore it and hit submit without it failing. Seems like I need something in my controller file (posted above). Just not sure what.

You must define rules for each field, and then check in the controller whether the rules are set.
```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        helper(['ci_multi_captcha', 'form', 'url']);


        if (!$this->request->is('post')) {
            return view('welcome_message');
        }

        $rules =[
            'fname' => [
                'label' => 'Test.fname',
                'rules' => 'required|in_list[pooya,ali]',
            ],
            CIMC_FIELD('arcaptcha') => CIMC_RULE(),

        ];

        if (!$this->validate($rules)) {
            return redirect()->back()->withInput()->with('errors', $this->validator->getErrors());
        }

        return redirect()->back()->withInput()->with('message', 'all field is OK!');


    }
}

```

**Comment by MarcPinnell** [comment]
Doesn't look like you advanced the version number, can I just update the files I see that have been touched manually in the vendor folder or is there a better way?

**Comment by datamweb** [comment]
In **CI4-project-root/composer.json**
add  `"datamweb/codeigniter-multi-captcha":"dev-main"`
```json
  "require": {
        "php": "^7.4 || ^8.0",
        "codeigniter4/framework": "^4.0",
        "datamweb/codeigniter-multi-captcha":"dev-main"
    },
```
Run :
```console
composer update
```
OR [Download](https://github.com/datamweb/codeIgniter-multi-captcha/archive/refs/heads/main.zip) and [instal manually](https://github.com/datamweb/codeIgniter-multi-captcha#the-second-method-manually)

**Comment by MarcPinnell** [comment]
> > If you are going to do another version, might want to move the keys to the .env file so they don't get overwritten when doing updates via composer.
> 
> Added two features:
> 
> 1. Command `cimc:publish `
>    To use it, run the following command.
>    ```
>    php spark cimc:publish
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Then go to **app/Config/MultiCaptchaCIConfig.php** and set the keys (or any other properties).


[CodeIgniter\Files\Exceptions\FileException]

__construct expects a valid directory.

at SYSTEMPATH/Files/FileCollection.php:52

Backtrace:
  1    SYSTEMPATH/Files/FileCollection.php:52
       CodeIgniter\Files\Exceptions\FileException::forExpectedDirectory()

  2    SYSTEMPATH/Publisher/Publisher.php:159
       CodeIgniter\Files\FileCollection::resolveDirectory()

  3    VENDORPATH/datamweb/codeigniter-multi-captcha/CIMultiCaptcha/Commands/CIMCaptchaPublish.php:35
       CodeIgniter\Publisher\Publisher()->__construct()

  4    SYSTEMPATH/CLI/Commands.php:65
       Datamweb\CIMC\Commands\CIMCaptchaPublish()->run()

  5    SYSTEMPATH/CLI/Console.php:37
       CodeIgniter\CLI\Commands()->run()

  6    ROOTPATH/spark:97
       CodeIgniter\CLI\Console()->run()

**Comment by datamweb** [comment]
I have made some changes, can you install a **clean version of the codeigniter framework** and then install **codeigniter-multi-captcha** with the command below?

```console
composer require datamweb/codeigniter-multi-captcha:dev-main
```

**Comment by MarcPinnell** [comment]
Not sure what you mean about a clean version of framework? This is a large app, I can't delete it.

I did try deleting the datamweb directory from vendor then running composer require like you said and it restored the directory, but I am still getting the same error when I try to the publish command.

With that said I looked at the code in the publish command and manually applied the replacements to a copy of the config file (after moving it) and it seems to be working.

**Comment by MarcPinnell** [comment]
Now when I submit the contact form I am getting: ""hcaptcha" is not a valid rule." with this code:

```
		$post = $this->request->getPost();

		$rules =[
			CIMC_FIELD('hcaptcha') => CIMC_RULE(),
		];

		if (!$this->validate($rules)) {
			return redirect()->back()->withInput()->with('errors', $this->validator->getErrors());
		}

		return redirect()->back()->withInput()->with('message', 'all field is OK!');

```

The required helpers are in the basecontroller

**Comment by datamweb** [comment]
> Now when I submit the contact form I am getting: ""hcaptcha" is not a valid rule." with this code:

Go to the app/Config path and add the following values in the Validation.php file.   
```php
 public $ruleSets = [
        // Add this line
        '\Datamweb\CIMC\Validation\RulesCIMC',
    ];
    public $templates = [
        // Add this line
        'CIMC_ERRORS_LIST'      => 'Datamweb\CIMC\Validation\Views\_list.php',
        // Add this line
        'CIMC_ERRORS_SINGLE'    => 'Datamweb\CIMC\Validation\Views\_single.php',
    ];
```

Have you added file`app\Config\Autoload.php` like below?

    public $psr4 = [
        APP_NAMESPACE => APPPATH, // For custom app namespace
        'Config'      => APPPATH . 'Config',
        'Datamweb\CIMC' 	        => APPPATH . 'ThirdParty\CIMultiCaptcha',
    ];

And what is your CI framework version?

**Comment by MarcPinnell** [comment]
The $ruleSets was missing. Must have missed it when I was initially installing and had to redo it twice when I tried to switch to composer from manual.

Adding the ruleset fixed it.

I am running CI 4.3.3

**Comment by datamweb** [comment]
The error you are getting is probably due to the presence of `'Datamweb\CIMC' => APPPATH . 'ThirdParty\CIMultiCaptcha',` in file **app\Config\Autoload.php**.
delete it
```php
    public $psr4 = [
        APP_NAMESPACE => APPPATH, // For custom app namespace
        'Config'      => APPPATH . 'Config',
    ];

```
Then run command `php spark cimc:publish`, no error should be displayed.

**Comment by MarcPinnell** [comment]
Yep that did it!

Thanks for your patience working through this.

**Comment by datamweb** [comment]
Also the documentation is not good and I need to improve the documentation.

Currently, due to the existence of the demo file, the size of the package is very high, I will soon remove the demo file from the source.

Thanks!
